
name: Discord Bot Docker CI/CD

on: 
 workflow_dispatch:
 push:
  branches:
    - release
jobs:
  build-Docker-Image: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Obtaining the tag. . .
      uses: xom9ikk/version-by-tag@v1
      id: version_by_tag

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Login to Docker Hub. . .
      uses: docker/login-action@v2.1.0
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push the Image. . .
      uses: docker/build-push-action@v3.2.0
      with:
        build-args: --env-file .env.example up
        push: true
        tags: landerf/clara_oswlad:latest,landerf/clara_oswlad:release_${{steps.version_by_tag.outputs.tag}}
